### ISSUE TITLE
uwsgi.service fail to start - cannot complete commissioning

### ISSUE THREAD

**Issue by Strider3000** [morph1904/Tyger2#2]
Ubuntu Server LTS vanilla 18.04.3:
After install I get this:

Created symlink /etc/systemd/system/multi-user.target.wants/caddy.service ? /etc/systemd/system/caddy.service.
Created symlink /etc/systemd/system/multi-user.target.wants/uwsgi.service ? /etc/systemd/system/uwsgi.service.
Job for uwsgi.service failed because the control process exited with error code.
See "systemctl status uwsgi.service" and "journalctl -xe" for details.

Install log here: http://paste.ubuntu.com/p/v3tWQTqJgf/
Result of "systemctl status uwsgi.service" here: http://paste.ubuntu.com/p/x64RzwjhjF/
Result of "journalctl -xe" here: http://paste.ubuntu.com/p/wYztD7nZfv/

**Comment by morph1904** [comment]
Hi Strider,

It looks like uwsgi has not installed correctly. 

This section of your logs is giving the clue:

>  Unit uwsgi.service has begun starting up.
Aug 27 13:50:11 tc2 systemd[2688]: uwsgi.service: Failed to execute command: No such file or directory
Aug 27 13:50:11 tc2 systemd[2688]: uwsgi.service: Failed at step EXEC spawning /usr/local/bin/uwsgi: No such file or directory
-- Subject: Process /usr/local/bin/uwsgi could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The process /usr/local/bin/uwsgi could not be executed and failed.
-- 
-- The error number returned by this process is 2.
Aug 27 13:50:11 tc2 systemd[1]: uwsgi.service: Main process exited, code=exited, status=203/EXEC
Aug 27 13:50:11 tc2 systemd[1]: uwsgi.service: Failed with result 'exit-code'.
Aug 27 13:50:11 tc2 systemd[1]: Failed to start uWSGI Emperor service.
-- Subject: Unit uwsgi.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit uwsgi.service has failed.

This was caused by multiple issues which should now be resolved. 

To complete a successful install please remove the /apps directory and all contents, remove the /tmp/install-ubuntu.sh file and follow the installation steps. 

Morph
