### ISSUE TITLE
Multiple menu icons

### ISSUE THREAD

**Issue by andyjhall** [morph1904/Tyger2#8]
Looks like the dashboard has multiple menu icons:
![1](https://user-images.githubusercontent.com/989064/64949148-773e0200-d870-11e9-9a83-68d50b658511.PNG)

**Comment by andyjhall** [comment]
I'd even argue that the menu isn't needed as all options are available on the main dashboard.

**Comment by morph1904** [comment]
Hi Andy, 

Thanks for this. 

Although this does look odd and unnecessary, it is actually intentional. They are placeholders for further features and updates.

I will close this as an issue as it is intentional, but you should see them change into more useful things over the next month or two. 

Morph
